name: Check Bun App
# description: Run all test for a bun application.

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Current Working directory (Useful for mono-repo)'
        required: false
        default: '.'
      bun-version:
        type: string
        description: 'Version of Bun to use'
        required: false
        default: 'latest'
      artifact-name:
        type: string
        description: 'Give artifact name for coverage report'
        required: false
      artifact-path:
        type: string
        description: 'Coverage report path to upload as artifact'
        required: false
        default: 'coverage/lcov.info'
    outputs:
      artifact-id:
        description: 'The ID of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-id }}
      artifact-url:
        description: 'The URL of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-url }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ${{inputs.working-directory}}/node_modules
          key: ${{ runner.os }}-bun-web-${{ hashFiles(format('{0}/bun.lock', inputs.working-directory)) }}
          restore-keys: ${{ runner.os }}-bun-web-

      - name: Install Bun dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun test --coverage --coverage-reporter=lcov --coverage-dir=./coverage
        
      - id: upload-artifact
        name: Upload artifact
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.artifact-path }}
